language: java
jdk:
- oraclejdk8
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Y58g8Bf/ZuEQXMLu/L2MDsp7oALblhBIJKDS9xqqiCLRFOPCtjRgw1Y0uHUWDRx9GgmZCa6XYgx1m4pU1cy+a1gSPCSPBVcdlt8Ww2fxK90l/hUSkBqToBheXGlVY3iOAMSDVYkx5qlmAWyQ9o5nh0BvO7/mVmNOPWk7b7Rvhtw3xcanbM6zDYh2FcKcfGkAYybHd4NC3ByMIozHWgDfKZVtjURDwnbNsQhDO/i2Rn1muIzPXbz1dHKhGhHYaLuGaoaq79twhurycIkXPArWENpavGENK2zP8dhZKw5c9kJ2iMOKARbmVo9krEyVXR3AWzrUrr2grQH+jkqvyLol8zRWZ1XJs92zL7i2MjN0peQBNfpAmeFGTI06jkRhHw+j4CicJ8TC1RRmEMrwVauScUs6DK9qOViumkROh8EKh0pQLFug1x/KMgi6/b7UP1tDZhAzHve5rdWsIoMtXtXkKnSZ5BN441JLpJEQNqjfj5A5LwjQCqj0JDBIj77V+EnM6QbjTcrUDjCZvqPzYSlL1AaaiJ6vHYuBado/CqWlffqHRN/3Kx0ov4Ryk4zpmLKjGfGrfB5mKioRm9q4UA9bn+LYvU60RZ52clGt0y2Z3FMezJh0Av7r0g2kpx4Q+XUDwnh/W/Aa0SXxF3yqLCEbM4vTpMazLxv9yygVeHUp24k=
  app: fast-stream-30461
  on:
    repo: salinnhanse/TicTacToe
