language: java
jdk:
- oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: jcroiCiAPxHNfBAZOoJ/65CfTDZo1rLZYQPgu7eTfz6VvU6DPn9gnPZ3rAhYWVc8bK+eZPhi6ADdFgRlxJyEj2LYPLc2HvWRpvoFEMl2KBQnYYJk9ps93qYB9/X+VzkIfoRSa90fxdXM/M5tpDD4tVr/SgX7jH3MxXycxVWyw8BgKjdKREdNn4iU2l+mWmN1r0+2uN93eu06bvkFjyO0suodd/ekYqx+LzEezd/yXUh3JPrStek76iRO/YfWVTGQSHNA7N335lD/BEyP9HSxBGSc0Nhcgycd8RcOeRH4dI5MnNwvfJz/hMbDKa5rTbxYCqIKbEztlq1ByKNd8DsX9AuYM3CGZTNsuL2/4rcqGdZsKOV4ONEiFDiovLoG1qAB8zuis7EiJHimkv7t5K/qeg0Mw1ZgDFNBj+LwOxEqzeW8lIX8BwmZ35y3o32WxqOfb52GVzUrv7m3awGwvhwsbaLcXoISQF3pJ2VjC8NyLGfYMkVSXc5UXwGtDzGF2LhvQJwiNMVqaB8XEWWy0XjonRDGTPI21fO5vgDVfc6ujUdM1FJnYlxuvOyho+ch99H4hoSi64lLIINBiWe9+WCVDEE/oMZrluvyixpDheSHp7fixu/vBnr5DpD+rqvHXZxfcCFIDQ3kSo+hBPJqsUXR97zzmEhqVqaoJksaMgvWsWA=
  app: secure-river-66674
  on:
    repo: salinnhanse/TicTacToe
